FROM scireum/s3-ninja:6.4 

USER sirius

# Inclua todos os buckets que precisa no comando a seguir

CMD mkdir -p /home/sirius/data/seu_primeiro_bucket && \
    mkdir -p /home/sirius/data/seu_segundo_bucket && \
    /home/sirius/run.sh